extends: 
- "spectral:oas"
- "@stoplight/spectral-owasp-ruleset"
# - "@apisyouwonthate/style-guide"

rules:
  operation-tags: false
  owasp:api4:2019-array-limit: false
  owasp:api4:2019-string-limit: false
  owasp:api4:2019-string-restricted: false
