openapi: 3.1.0
info:
  title: Train Travel API
  description: API for finding and booking train trips across Europe.
  version: 1.0.0
  contact:
    name: Train Support
    url: https://example.com/support
    email: support@example.com

servers:
  - url: https://api.example.com
    description: Production

# Paths split into separate files
paths:
  /stations:
    $ref: paths/stations.yaml
  /trips:
    $ref: paths/trips.yaml
  /bookings:
    $ref: paths/bookings.yaml

# Applies the OAuth2 security scheme to all operations
security:
  - OAuth2:
      - read

# Reusable components
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Read access
            write: Write access
