openapi: 3.1.0
info:
  title: Train Travel API
  description: API for finding and booking train trips across Europe.
  version: 1.0.0
  contact:
    name: Train Support
    url: https://example.com/support
    email: support@example.com

servers:
  - url: https://api.example.com
    description: Production

tags:
  - name: Stations
    description: >-
      Find and filter train stations across Europe, including their location 
      and local timezone.

  - name: Trips
    description: >-
      Timetables and routes for train trips between stations, including 
      pricing and availability.

  - name: Bookings
    description: >-
      Create and manage bookings for train trips, including passenger 
      details and optional extras.

# Paths split into separate files
paths:
  /stations:
    $ref: paths/stations.yaml
  /trips:
    $ref: paths/trips.yaml
  /bookings:
    $ref: paths/bookings.yaml

# Events created by the API
webhooks:
  newBooking:
    $ref: webhooks/new-booking.yaml

# Applies the OAuth2 security scheme to all operations
security:
  - OAuth2:
      - read

# Reusable components
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Read access
            write: Write access
